In [1]:
import numpy as np

In [2]:
my_list = [i for i in range(10)]
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
my_array = np.array(my_list)
my_array ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
my_matrix[:,2:3]

array([[3],
       [6],
       [9]])

* # arange

In [9]:
x = np.linspace(1,25,36)
x

array([ 1.        ,  1.68571429,  2.37142857,  3.05714286,  3.74285714,
        4.42857143,  5.11428571,  5.8       ,  6.48571429,  7.17142857,
        7.85714286,  8.54285714,  9.22857143,  9.91428571, 10.6       ,
       11.28571429, 11.97142857, 12.65714286, 13.34285714, 14.02857143,
       14.71428571, 15.4       , 16.08571429, 16.77142857, 17.45714286,
       18.14285714, 18.82857143, 19.51428571, 20.2       , 20.88571429,
       21.57142857, 22.25714286, 22.94285714, 23.62857143, 24.31428571,
       25.        ])

In [11]:
b = x.reshape(6,6)
b

array([[ 1.        ,  1.68571429,  2.37142857,  3.05714286,  3.74285714,
         4.42857143],
       [ 5.11428571,  5.8       ,  6.48571429,  7.17142857,  7.85714286,
         8.54285714],
       [ 9.22857143,  9.91428571, 10.6       , 11.28571429, 11.97142857,
        12.65714286],
       [13.34285714, 14.02857143, 14.71428571, 15.4       , 16.08571429,
        16.77142857],
       [17.45714286, 18.14285714, 18.82857143, 19.51428571, 20.2       ,
        20.88571429],
       [21.57142857, 22.25714286, 22.94285714, 23.62857143, 24.31428571,
        25.        ]])

In [13]:
x = np.eye(4,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [15]:
'''rand ---> create an array of the given shape and 
   populate it with random samples from a uniform distribution over [0,1)'''

'''randn return a sample (or samples) from the "standard normal" 
   distribution. Unlike rand which is uniform'''



array([[-0.66367681,  0.87023197, -0.51344018,  0.27161847],
       [-1.28679804, -1.25677163, -0.75019788,  0.35310762],
       [-1.28324856, -0.09568816, -0.68455146,  0.51831453],
       [-0.45914065, -0.51041725, -1.55284738,  0.2322272 ],
       [-0.21548688, -0.65319679,  1.13902061, -0.6884673 ]])

In [ ]:
a = [i for i in range(10)]
